### ISSUE TITLE
Improvement to small size gridmode

### ISSUE THREAD

**Issue by pernyl** [qlik-oss/sn-list-objects#179]
1: Create a FP 
2: Set properties to gridmode and to just one row
3: Make the FP so that it is small just one line

- Notice that you yourself need to remove the title to get a goodlooking one line vertikal FP

It would be nice if you make a listbox in grid mode on one line that the title would be removed (but only when grid mode).

https://qlikdev.slack.com/archives/C03UNNA04BE/p1679385869946809

![abc!](https://user-images.githubusercontent.com/29114032/226547430-bcb722cc-8c08-40c4-98af-0400a13f3980.gif)

**Comment by DanielS-Qlik** [comment]
Auto hiding title comes with some strange behaviours, as you can see in https://github.com/qlik-oss/nebula.js/pull/1175.
Since the height can change depending on how you resize your browser, one user can have the title visible while another user can have it hidden.
Adding a checkbox for hiding title in pp here instead: https://github.com/qlik-oss/sn-list-objects/pull/203
